- index.js
- test/all.js
`encRange` takes a `sub` option that's currently not set by any of the iterators. This PR fixes that and updates the short iterators test to check for out-of-bounds reads.
> Fix sub bug

- index.js
- iterators/diff.js
- iterators/range.js
When reading over the code I noticed that the `cmp` operation is using `>` instead of `Buffer.compare`. The problem is that these operations are not equal (see [this gist](https://gist.github.com/martinheidegger/3ea2ea920073c9a69f464ff153af27d1)) and it seems that the buffer comparison may be using the `.toString()` value of `Uint8Array`s for comparison? In any case, [I tested the performance](https://jsbench.me/ipkisazwkq/1) for the methods and the result is that `Buffer.compare` is a **lot** faster than `>`. Which is why this PR replaces `cmp` with `Buffer.compare`.
> Replaces "cmp" with "Buffer.compare".

- index.js
Since each sub-database is a separate Hyperbee, a _ready Promise needs to be passed in order to prevent appending the Header several times.
> Sub and checkouts pass _ready opt

- index.js
- package.json
With the hypercore-promisifier module, and `feed` passed into the constructor will be wrapped in a Promises API.
> Use a Promises-only Hypercore API with hypercore-promisifier

- index.js
- test/all.js
Adds a `readonly` constructor option that when `true` will disable writing the Header + any appends.
> Add readonly constructor option

- index.js
- test/all.js
Hyperbee internally promisifies its feed using `hypercore-promisifier`, but then `db.feed` is set to the promisified version. One would expect the feed passed into the constructor to be equal to `db.feed`.
This PR adds a `db.feed` getter, which unwraps the internal feed.
Relevant issue on `hypercore-promisifier`: https://github.com/andrewosh/hypercore-promisifier/issues/1
> Add de-promisifying getter for feed property 

- index.js
This check should be Hypercore's responsibility, so no need for Hyperbee to have additional handling here.
> Remove writability check in getRoots

- index.js
- test/all.js
- test/diff.js
Fixes a bug where calling `checkout` on a `sub` will lead to incorrect iteration results on all iterators because the `keyEncoding` is recomputed inside the checkout. Instead, the checkout should use the parent's `keyEncoding`.
> Fixed checkout/sub behavior

- index.js
- test/diff.js
https://github.com/hypercore-protocol/hyperbee/pull/35 fixed a bug where `db.sub().checkout()` would not produce valid iterators, but unfortunately it introduced another bug where `db.checkout().sub()` would not have the correct `keyEncoding` on any sub databases.
This fix introduces two hidden constructor options (`_sub` and `_checkout`) that are used to distinguish between the following two cases:
1. If a Hyperbee is constructed with a prefix, and it is explicitly constructed from a `sub` call, then the `keyEncoding` should be updated
2. If a Hyperbee is constructed with a prefix, but as a result of a call to `checkout`, then the `keyEncoding` should not be updated.
Phew. Also added another sub/checkout/createDiffStream test for this scenario.
> Fix checkout/sub bug

- index.js
When the extension is disabled in the parent (via `extension: false`), sub databases will currently still attempt to register it, because this option is overridden.
This fix ensures that `extension: false` disables the extension in all sub databases as well.
> Fix extension disabling bug

- index.js
- iterators/diff.js
- iterators/history.js
- iterators/range.js
- test/helpers/index.js
Right now we insert the header eagerly in `ready`. With this change, the header will be inserted before the first write operation instead.
> Lazily insert header on first write

- README.md
- index.js
- test/all.js
- test/cas.js
Adds the ability to compare and swap on a key in a Hyperbee. In particular, if we have:
* a hyperbee: `bee`
* a key: `key`
* a value we want to set: `value`
* the current value in `bee` at `key`: `current`
* a value we want to compare against `current`: `test`
* and a predicate that will compare `test` and the current value in `bee` at `key`: `compare`
Then `Hyperbee.cas()` compares `current` and `test` through `compare` and:
if `true`: sets `key` at `value` in `bee` and returns `current`
if `false`: return `null`
The default `compare` function encodes `test` through `bee.valueEncoding` and compares against the encoded value of `current`.
> Adds Compare And Swap to Hyperbee

- index.js
- test/cas.js
In a world without cas, it is impossible for a batch to be both mutated AND for the batch to have a length equal to zero; that is, in a cas-less world every batch operation makes progress. Once we introduce cas, it is possible for us to abort an op on a batch. Since batch.flush() always makes progress regardless of batch size, it is possible for flush to return after we bailed from a batch op (bc cas "failed") without releasing the bee lock that is acquired during every batch mutation.
This PR fixes this bug and adds test to detect it in the future.
> Fixes deadlock bug on `flush` of empty batch after failed `cas`

- README.md
-Both the delete and put examples accidentally specified the valueEncoding twice (and no keyEncoding)
-The delete example's put operation was incorrect (it didn't put anything due to the cas)
> Fix ReadMe cas examples

- index.js
- iterators/diff.js
- iterators/history.js
- iterators/range.js
- test/batches.js
`Batch.put` and `Batch.get` will both currently use the Batch's default key/value encodings always. This PR lets that be overridden.
Edit: Also added support for custom key encodings to `Batch.del` and `Batch.createReadStream`
> Support key/value encodings in Batch.put/Batch.get

- README.md
- index.js
- package.json
- test/all.js
- test/helpers/index.js
Note: this test flags some hyperbees which are usable as invalid. It happens if they are created from cores to which had already been pushed. Not sure what the intended behaviour is there--we could check `isHyperbee(this)`  in `ready()`, but it seems like a big change to suddenly disallow the below:
```
import Hypercore from 'hypercore'
import ram from 'random-access-memory'
import Hyperbee from 'hyperbee'
const core = new Hypercore(ram)
await core.ready()
await core.append('Random stuff')
const bee = new Hyperbee(core)
await bee.ready()
await bee.put('This is', 'okay?')
console.log((await core.get(0)).toString()) // 'Random stuff'
console.log((await bee.get('This is')).value.toString()) // 'okay?'
console.log(await bee.getHeader()) // This crashes with `Error: Decoded message is not …
```
> Add isHyperbee

- index.js
- iterators/history.js
Previously, we would pass `update: false` directly to `batch.get(...)`, but it makes more sense to set this option at the batch-level.
> Batch supports the update option

- README.md
- index.js
We refer to Hypercore as "cores" everywhere else, so we should do the same here.
> Alias bee.core to bee.feed

- index.js
- test/diff.js
The `keyEncoding` option to `createDiffStream` is currently being ignored.
> Fix diff key encoding opt

- README.md
- index.js
- test/all.js
I think my initial implementation of isHyperbee was wrong, because I didn't fully understand what the patterns with the `wait` (or `timeout`) options were.
Previous:
If empty core => return false
New:
If empty core => Wait set ? return null : wait on first block
Feel free to close if the previous behaviour was the expected one--I can easily get around this.
Still not very happy with this solution, since it's a boolean check with 3 possible outcomes, which is super weird. But I don't see another way to support the ready() pattern of hyperdrive if it depends on isHyperbee: 
```
async _open () {
await this._doFancySetup({wait: false})
if(!this.setupDone) {
this._doFancySetup()
}
...
}
async _doFancySetup (opts) {
const isBee = await Hyperbee.isHyperbee(this._core, opts)
if (isBee === null) …
```
> Make isHyperbee wait or return null for empty core

- index.js
- test/all.js
Note: opted to only pass key- and valueEncoding rather than passing through the `...opts` to the Hyperbee constructor because I'm not sure if it makes sense to support (all) other options. Can adapt
> Support encoded checkout

- index.js
Note: irrelevant for bees based on normal hypercores, so only added if autobase(-next)
> Add truncate listener to watcher

- README.md
- index.js
- test/watch.js
This is not just a refactor, the behaviour changes subtly.
I think that in the previous version there was a race condition on calling next before the watcher was ready, but it never triggered. I had to add `if (!this.opened) await this.ready()` to `Watcher.next()` to make the tests pass. I think `next()` is the only entrypoint, so should be fine to just add this check there.
Also in `next()`:       `if (this.closed) return { value: undefined, done: true } ` had to change to `if (this.closing)`, because `this.closing` and `this.closed` are no longer set in the same tick now that we're using ready resource. Likewise for the test I changed.
There's another method where I'm not sure if it should also change to `closing`: 
```
async _waitForChanges () {
if (this.current.version < …
```
> Use ready-resource for watcher

- README.md
- index.js
- package.json
- test/watch.js
Two behaviours were somewhat unexpected, both related to truncates:
In the 'getAndWatch truncate flow' test, I think we're hitting a race condition on `await this.bee.get(this.key)`, where a truncate is triggered ~at the same time as the get. This results in a `SNAPSHOT_NOT_AVAILABLE` error.
This one is solved by catching that particular error and early-returning, because we know it was triggered by a truncate, so `_onAppend` will run again anyway. But if it is indeed a race condition, I think it should be solved elsewhere in the code.
In the 'getAndWatch chaos' test, there's still a TODO, because I had to add an `await eventFlush()` to avoid a crash, and I don't think it should be necessary. It might be a similar scenario to the error above, but I'm not sure. The error is
``` …
```
> Add getAndWatch

- test/diff.js
So far, only the case where a version number is passed was explicitly tested. Seems to work fine though
> Test diff stream with passed hyperbees

- index.js
If `reuseSessions` is currently set, it'll create a new Hyperbee with a Hyperbee as the first arg.
> Fix checkout with reuseSessions bug

- README.md
Thanks @HDegroote the initial explanation: https://github.com/holepunchto/hyperbee/pull/90/commits/08a3fcac5422ea32f6149d3983479e8579f5439b
I didn't even know that we had a lock method lol
> Improve batch docs

- README.md
- index.js
- test/basic.js
If you're using a Hyperbee then there should be no need to constantly access to `db.core`
Yes, they're just core aliases but makes the bee experience better
Closes https://github.com/holepunchto/hyperbee/issues/128
> Add aliases for core properties, and fix update options

- index.js
`Header.decode` can throw RangeErrors because of varint (https://github.com/chrisdickinson/varint/blob/7fc8829334c20c4c0e246e3b473c1eb1c03ebbf9/decode.js#L17). RangeErrors get thrown by safetyCatch, so we need to ignore all errors here
> isHyperbee: no safetyCatch on failed decode

- index.js
- package.json
- test/cache.js
Draft because it relies on https://github.com/holepunchto/unslab/pull/1
(can also work without above PR, but then hyperbee needs to special-case the null entries before calling unslab)
> Use unslab to simplify copyEntry + add test

- README.md
- index.js
- package.json
- test/cache.js
Depends on https://github.com/holepunchto/hypercore/pull/535 for it to really make sense
This makes the node- and key cache derive from the same rache.
It removes the `maxCacheSize` opt, which is made redundant (technically a breaking change, but very recently added, and passing it in anyway won't cause any issues).
Note: this PR changes the ready flow (the caches can now only be set after `this.core` is ready). Using the caches before the bee is ready doesn't make sense, so that should be fine.
The flow when a `globalCache` is set on the underlying `Hypercore` makes sense: all caches along all sessions then derive from the same `globalCache`.
But when no `globalCache` was set on the hypercore, each checkout/session will still create its own separate caches. This doesn't really make …
> Derive node and key cache from shared rache

- index.js
This PR adds error handling for Header block decode. In case of `RangeError` in decoding, getHeader will throw `DECODING_ERROR` instead.
> catch range error on header block decoding

- README.md
Hypercore storage no longer supports `random-access-memory` and other `random-access-storage` instances.
> Remove RAM usage in README.md example
